### ISSUE TITLE
IndexError: list index out of range by running sabd.py

### ISSUE THREAD

**Issue by happygirlzt** [irving-muller/soft_alignment_model_bug_deduplication#2]
Hi there,

Many thanks for your amazing work! I used the eclipse dataset and embeddings provided by you (https://zenodo.org/record/3922012). I used the following code: 
`python3 experiments/sabd.py  -F ./experiments with ./json_parameters/sabd_eclipse_test.json "recall_rate.window=365"` 
However, there is a bug reported as follows:
<img width="940" alt="Screenshot 2020-12-22 at 18 53 23" src="https://user-images.githubusercontent.com/15061984/102881205-78a0a600-4487-11eb-9eb3-a5b745e99341.png">. Is there any part I need to modify in order to run your approach? Many thanks! :D

**Comment by irving-muller** [comment]
Hello,

Thank you for reporting this issue.

After some investigation, I discover that this bug was occurring due to the compability problem with the latest versions of ignite. I plan to fix it in near future. However, for now, I recommend you to use the ignite version 1.2. You can downgrade ignite by running the following command: `conda install -c pytorch ignite=0.1.2`

Please let me know if this does not fixed the problem.

**Comment by happygirlzt** [comment]
Hi there,

Many thanks for your help. The aforementioned command can run after setting pytorch-ignite == 0.1.2. 👍. For those who use pip, just run `pip install pytorch-ignite==0.1.2` 😀
